// Code generated by MockGen. DO NOT EDIT.
// Source: gateway.go
//
// Generated by this command:
//
//	mockgen -source=gateway.go -destination=mocks/gateway_mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	googletasksync "github.com/prepin/tick-sync/internal/usecase/googletasksync"
	gomock "go.uber.org/mock/gomock"
)

// MockGoogleTasksGateway is a mock of GoogleTasksGateway interface.
type MockGoogleTasksGateway struct {
	ctrl     *gomock.Controller
	recorder *MockGoogleTasksGatewayMockRecorder
	isgomock struct{}
}

// MockGoogleTasksGatewayMockRecorder is the mock recorder for MockGoogleTasksGateway.
type MockGoogleTasksGatewayMockRecorder struct {
	mock *MockGoogleTasksGateway
}

// NewMockGoogleTasksGateway creates a new mock instance.
func NewMockGoogleTasksGateway(ctrl *gomock.Controller) *MockGoogleTasksGateway {
	mock := &MockGoogleTasksGateway{ctrl: ctrl}
	mock.recorder = &MockGoogleTasksGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGoogleTasksGateway) EXPECT() *MockGoogleTasksGatewayMockRecorder {
	return m.recorder
}

// Complete mocks base method.
func (m *MockGoogleTasksGateway) Complete(ctx context.Context, taskID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Complete", ctx, taskID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Complete indicates an expected call of Complete.
func (mr *MockGoogleTasksGatewayMockRecorder) Complete(ctx, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Complete", reflect.TypeOf((*MockGoogleTasksGateway)(nil).Complete), ctx, taskID)
}

// Delete mocks base method.
func (m *MockGoogleTasksGateway) Delete(ctx context.Context, taskID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, taskID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockGoogleTasksGatewayMockRecorder) Delete(ctx, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockGoogleTasksGateway)(nil).Delete), ctx, taskID)
}

// ListUncompleted mocks base method.
func (m *MockGoogleTasksGateway) ListUncompleted(ctx context.Context) ([]googletasksync.GoogleTaskView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUncompleted", ctx)
	ret0, _ := ret[0].([]googletasksync.GoogleTaskView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUncompleted indicates an expected call of ListUncompleted.
func (mr *MockGoogleTasksGatewayMockRecorder) ListUncompleted(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUncompleted", reflect.TypeOf((*MockGoogleTasksGateway)(nil).ListUncompleted), ctx)
}

// MockTickTickGateway is a mock of TickTickGateway interface.
type MockTickTickGateway struct {
	ctrl     *gomock.Controller
	recorder *MockTickTickGatewayMockRecorder
	isgomock struct{}
}

// MockTickTickGatewayMockRecorder is the mock recorder for MockTickTickGateway.
type MockTickTickGatewayMockRecorder struct {
	mock *MockTickTickGateway
}

// NewMockTickTickGateway creates a new mock instance.
func NewMockTickTickGateway(ctrl *gomock.Controller) *MockTickTickGateway {
	mock := &MockTickTickGateway{ctrl: ctrl}
	mock.recorder = &MockTickTickGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTickTickGateway) EXPECT() *MockTickTickGatewayMockRecorder {
	return m.recorder
}

// CreateInboxTask mocks base method.
func (m *MockTickTickGateway) CreateInboxTask(ctx context.Context, input googletasksync.CreateTickTickTaskInput) (googletasksync.TickTickTaskView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInboxTask", ctx, input)
	ret0, _ := ret[0].(googletasksync.TickTickTaskView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateInboxTask indicates an expected call of CreateInboxTask.
func (mr *MockTickTickGatewayMockRecorder) CreateInboxTask(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInboxTask", reflect.TypeOf((*MockTickTickGateway)(nil).CreateInboxTask), ctx, input)
}
