// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=mocks/repository_mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	googletasksync "github.com/prepin/tick-sync/internal/usecase/googletasksync"
	gomock "go.uber.org/mock/gomock"
)

// MockSyncedTaskRepository is a mock of SyncedTaskRepository interface.
type MockSyncedTaskRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSyncedTaskRepositoryMockRecorder
	isgomock struct{}
}

// MockSyncedTaskRepositoryMockRecorder is the mock recorder for MockSyncedTaskRepository.
type MockSyncedTaskRepositoryMockRecorder struct {
	mock *MockSyncedTaskRepository
}

// NewMockSyncedTaskRepository creates a new mock instance.
func NewMockSyncedTaskRepository(ctrl *gomock.Controller) *MockSyncedTaskRepository {
	mock := &MockSyncedTaskRepository{ctrl: ctrl}
	mock.recorder = &MockSyncedTaskRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSyncedTaskRepository) EXPECT() *MockSyncedTaskRepositoryMockRecorder {
	return m.recorder
}

// GetSyncState mocks base method.
func (m *MockSyncedTaskRepository) GetSyncState(ctx context.Context, googleTaskID string) (googletasksync.SyncState, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSyncState", ctx, googleTaskID)
	ret0, _ := ret[0].(googletasksync.SyncState)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetSyncState indicates an expected call of GetSyncState.
func (mr *MockSyncedTaskRepositoryMockRecorder) GetSyncState(ctx, googleTaskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSyncState", reflect.TypeOf((*MockSyncedTaskRepository)(nil).GetSyncState), ctx, googleTaskID)
}

// MarkGoogleTaskFinalized mocks base method.
func (m *MockSyncedTaskRepository) MarkGoogleTaskFinalized(ctx context.Context, googleTaskID string, finalizedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkGoogleTaskFinalized", ctx, googleTaskID, finalizedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkGoogleTaskFinalized indicates an expected call of MarkGoogleTaskFinalized.
func (mr *MockSyncedTaskRepositoryMockRecorder) MarkGoogleTaskFinalized(ctx, googleTaskID, finalizedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkGoogleTaskFinalized", reflect.TypeOf((*MockSyncedTaskRepository)(nil).MarkGoogleTaskFinalized), ctx, googleTaskID, finalizedAt)
}

// SaveSyncedTask mocks base method.
func (m *MockSyncedTaskRepository) SaveSyncedTask(ctx context.Context, params googletasksync.SaveSyncedTaskParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveSyncedTask", ctx, params)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveSyncedTask indicates an expected call of SaveSyncedTask.
func (mr *MockSyncedTaskRepositoryMockRecorder) SaveSyncedTask(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveSyncedTask", reflect.TypeOf((*MockSyncedTaskRepository)(nil).SaveSyncedTask), ctx, params)
}
