// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=mocks/repository_mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	googletasksync "github.com/prepin/tick-sync/internal/usecase/googletasksync"
	gomock "go.uber.org/mock/gomock"
)

// MockSyncedTaskRepository is a mock of SyncedTaskRepository interface.
type MockSyncedTaskRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSyncedTaskRepositoryMockRecorder
	isgomock struct{}
}

// MockSyncedTaskRepositoryMockRecorder is the mock recorder for MockSyncedTaskRepository.
type MockSyncedTaskRepositoryMockRecorder struct {
	mock *MockSyncedTaskRepository
}

// NewMockSyncedTaskRepository creates a new mock instance.
func NewMockSyncedTaskRepository(ctrl *gomock.Controller) *MockSyncedTaskRepository {
	mock := &MockSyncedTaskRepository{ctrl: ctrl}
	mock.recorder = &MockSyncedTaskRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSyncedTaskRepository) EXPECT() *MockSyncedTaskRepositoryMockRecorder {
	return m.recorder
}

// IsProcessed mocks base method.
func (m *MockSyncedTaskRepository) IsProcessed(ctx context.Context, googleTaskID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsProcessed", ctx, googleTaskID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsProcessed indicates an expected call of IsProcessed.
func (mr *MockSyncedTaskRepositoryMockRecorder) IsProcessed(ctx, googleTaskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsProcessed", reflect.TypeOf((*MockSyncedTaskRepository)(nil).IsProcessed), ctx, googleTaskID)
}

// SaveSyncedTask mocks base method.
func (m *MockSyncedTaskRepository) SaveSyncedTask(ctx context.Context, params googletasksync.SaveSyncedTaskParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveSyncedTask", ctx, params)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveSyncedTask indicates an expected call of SaveSyncedTask.
func (mr *MockSyncedTaskRepositoryMockRecorder) SaveSyncedTask(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveSyncedTask", reflect.TypeOf((*MockSyncedTaskRepository)(nil).SaveSyncedTask), ctx, params)
}
