// Code generated by MockGen. DO NOT EDIT.
// Source: ports.go
//
// Generated by this command:
//
//	mockgen -source=ports.go -destination=mocks/mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	googletasksync "github.com/prepin/tick-sync/internal/usecases/googletasksync"
	gomock "go.uber.org/mock/gomock"
)

// MockGoogleTasksClient is a mock of GoogleTasksClient interface.
type MockGoogleTasksClient struct {
	ctrl     *gomock.Controller
	recorder *MockGoogleTasksClientMockRecorder
	isgomock struct{}
}

// MockGoogleTasksClientMockRecorder is the mock recorder for MockGoogleTasksClient.
type MockGoogleTasksClientMockRecorder struct {
	mock *MockGoogleTasksClient
}

// NewMockGoogleTasksClient creates a new mock instance.
func NewMockGoogleTasksClient(ctrl *gomock.Controller) *MockGoogleTasksClient {
	mock := &MockGoogleTasksClient{ctrl: ctrl}
	mock.recorder = &MockGoogleTasksClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGoogleTasksClient) EXPECT() *MockGoogleTasksClientMockRecorder {
	return m.recorder
}

// Complete mocks base method.
func (m *MockGoogleTasksClient) Complete(ctx context.Context, taskID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Complete", ctx, taskID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Complete indicates an expected call of Complete.
func (mr *MockGoogleTasksClientMockRecorder) Complete(ctx, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Complete", reflect.TypeOf((*MockGoogleTasksClient)(nil).Complete), ctx, taskID)
}

// Delete mocks base method.
func (m *MockGoogleTasksClient) Delete(ctx context.Context, taskID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, taskID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockGoogleTasksClientMockRecorder) Delete(ctx, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockGoogleTasksClient)(nil).Delete), ctx, taskID)
}

// ListUncompleted mocks base method.
func (m *MockGoogleTasksClient) ListUncompleted(ctx context.Context) ([]googletasksync.GoogleTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUncompleted", ctx)
	ret0, _ := ret[0].([]googletasksync.GoogleTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUncompleted indicates an expected call of ListUncompleted.
func (mr *MockGoogleTasksClientMockRecorder) ListUncompleted(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUncompleted", reflect.TypeOf((*MockGoogleTasksClient)(nil).ListUncompleted), ctx)
}

// MockTickTickClient is a mock of TickTickClient interface.
type MockTickTickClient struct {
	ctrl     *gomock.Controller
	recorder *MockTickTickClientMockRecorder
	isgomock struct{}
}

// MockTickTickClientMockRecorder is the mock recorder for MockTickTickClient.
type MockTickTickClientMockRecorder struct {
	mock *MockTickTickClient
}

// NewMockTickTickClient creates a new mock instance.
func NewMockTickTickClient(ctrl *gomock.Controller) *MockTickTickClient {
	mock := &MockTickTickClient{ctrl: ctrl}
	mock.recorder = &MockTickTickClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTickTickClient) EXPECT() *MockTickTickClientMockRecorder {
	return m.recorder
}

// CreateInboxTask mocks base method.
func (m *MockTickTickClient) CreateInboxTask(ctx context.Context, task googletasksync.TickTickTaskInput) (googletasksync.TickTickTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInboxTask", ctx, task)
	ret0, _ := ret[0].(googletasksync.TickTickTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateInboxTask indicates an expected call of CreateInboxTask.
func (mr *MockTickTickClientMockRecorder) CreateInboxTask(ctx, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInboxTask", reflect.TypeOf((*MockTickTickClient)(nil).CreateInboxTask), ctx, task)
}

// MockSyncStore is a mock of SyncStore interface.
type MockSyncStore struct {
	ctrl     *gomock.Controller
	recorder *MockSyncStoreMockRecorder
	isgomock struct{}
}

// MockSyncStoreMockRecorder is the mock recorder for MockSyncStore.
type MockSyncStoreMockRecorder struct {
	mock *MockSyncStore
}

// NewMockSyncStore creates a new mock instance.
func NewMockSyncStore(ctrl *gomock.Controller) *MockSyncStore {
	mock := &MockSyncStore{ctrl: ctrl}
	mock.recorder = &MockSyncStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSyncStore) EXPECT() *MockSyncStoreMockRecorder {
	return m.recorder
}

// IsProcessed mocks base method.
func (m *MockSyncStore) IsProcessed(ctx context.Context, googleTaskID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsProcessed", ctx, googleTaskID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsProcessed indicates an expected call of IsProcessed.
func (mr *MockSyncStoreMockRecorder) IsProcessed(ctx, googleTaskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsProcessed", reflect.TypeOf((*MockSyncStore)(nil).IsProcessed), ctx, googleTaskID)
}

// MarkProcessed mocks base method.
func (m *MockSyncStore) MarkProcessed(ctx context.Context, record googletasksync.SyncedTaskRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkProcessed", ctx, record)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkProcessed indicates an expected call of MarkProcessed.
func (mr *MockSyncStoreMockRecorder) MarkProcessed(ctx, record any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkProcessed", reflect.TypeOf((*MockSyncStore)(nil).MarkProcessed), ctx, record)
}
